# THIS FILE IS AUTOMATICALLY GENERATED
# Project: \\files.auckland.ac.nz\myhome\Documents\GitHub\project-project_group_15\WorkspacemotorBT1\Hardware2.cydsn\Hardware2.cyprj
# Date: Sun, 25 Sep 2022 03:37:22 GMT
#set_units -time ns
create_clock -name {ADC_SAR_Seq_1_IntClock(routed)} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/dclk_1}]]
create_clock -name {CyILO} -period 10000 -waveform {0 5000} [list [get_pins {ClockBlock/ilo}] [get_pins {ClockBlock/clk_100k}] [get_pins {ClockBlock/clk_1k}] [get_pins {ClockBlock/clk_32k}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyPLL_OUT} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/pllout}]]
create_clock -name {CyMASTER_CLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/clk_sync}]]
create_generated_clock -name {CyBUS_CLK} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2 3} [list [get_pins {ClockBlock/clk_bus_glb}]]
create_generated_clock -name {ADC_SAR_Seq_1_IntClock} -source [get_pins {ClockBlock/clk_sync}] -edges {1 3 7} [list [get_pins {ClockBlock/dclk_glb_1}]]
create_generated_clock -name {Clock_PWM} -source [get_pins {ClockBlock/clk_sync}] -edges {1 25 49} [list [get_pins {ClockBlock/dclk_glb_2}]]
create_generated_clock -name {Clock_QENC} -source [get_pins {ClockBlock/clk_sync}] -edges {1 3 5} [list [get_pins {ClockBlock/dclk_glb_0}]]
create_generated_clock -name {timer_clock_2} -source [get_pins {ClockBlock/clk_sync}] -edges {1 2401 4801} [list [get_pins {ClockBlock/dclk_glb_3}]]

set_false_path -from [get_pins {__ONE__/q}]

# Component constraints for \\files.auckland.ac.nz\myhome\Documents\GitHub\project-project_group_15\WorkspacemotorBT1\Hardware2.cydsn\TopDesign\TopDesign.cysch
# Project: \\files.auckland.ac.nz\myhome\Documents\GitHub\project-project_group_15\WorkspacemotorBT1\Hardware2.cydsn\Hardware2.cyprj
# Date: Sun, 25 Sep 2022 03:35:51 GMT
